### ISSUE TITLE
Passwords are not automatically remembered and put in by the browser

### ISSUE THREAD

**Issue by dennisvanmaren** [EnsembleUI/ensemble#153]

**Comment by kmahmood74** [comment]
@dennisvanmaren looks like this is an open issue on flutter for chrome - https://github.com/flutter/flutter/issues/87735
works on FireFox

**Comment by kmahmood74** [comment]
This has been fixed by Flutter. @amin-nas please confirm that this works now.

**Comment by amin-nas** [comment]
It is not fixed on Ensemble side:

Test app:
https://studio.ensembleui.com/preview/index.html?appId=grXE9uenRV4Yb6yMGyUB&showAction=true&devicePreview=true

Link to app in studio:
https://studio.ensembleui.com/app/grXE9uenRV4Yb6yMGyUB/screens

**Comment by amin-nas** [comment]
Fixed. Closing.
